import test from 'node:test';import assert from 'node:assert/strict';import {Runtime} from '../core/runtime.mjs';import {evaluate,ApprovalStore,seedMemory} from '../core/policy.mjs';import {localURL,rime,validateVoice,ollama,transcribe} from '../core/providers.mjs';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));function fixture(model,extra={}){const events=[],memory=structuredClone(seedMemory);const runtime=new Runtime({model,storage:{read:()=>memory,add:(m,active)=>{if(active())memory.push(m)}},emit:e=>events.push(e),...extra});return {runtime,events,memory}}
test('unknown and delete tools cannot execute',async()=>{for(const tool of ['shell','delete_memory']){const {runtime,events}=fixture(async()=>({action:{tool,args:{id:'all'}}}));await runtime.run('delete');assert.equal(events.find(e=>e.type==='policy').decision,'block');assert.equal(events.filter(e=>e.type==='tool').length,0)}});
test('memory write requires explicit approval and cannot replay',async()=>{const {runtime,events,memory}=fixture(async()=>({action:{tool:'save_memory',args:{title:'Priority',content:'Test voice'}}}));await runtime.run('remember');assert.equal(memory.length,6);const approval=events.find(e=>e.type==='approval');await runtime.approve(approval.approvalId,true);assert.equal(memory.length,7);await assert.rejects(runtime.approve(approval.approvalId,true));assert.equal(memory.length,7)});
test('denied approval never writes',async()=>{const {runtime,events,memory}=fixture(async()=>({action:{tool:'save_memory',args:{title:'Priority',content:'Test voice'}}}));await runtime.run('remember');await runtime.approve(events.find(e=>e.type==='approval').approvalId,false);assert.equal(memory.length,6)});
test('approval snapshot cannot be changed after evaluation',()=>{const store=new ApprovalStore(),a={tool:'save_memory',args:{title:'A',content:'Original'}},id=store.create(a,1);a.args.content='Mutated';assert.equal(store.take(id,1).args.content,'Original');const id2=store.create(a,1);assert.throws(()=>store.take(id2,2));const id3=store.create(a,1);store.pending.get(id3).expires=Date.now()-1;assert.throws(()=>store.take(id3,1))});
test('new turn invalidates old approval',async()=>{let n=0;const {runtime,events,memory}=fixture(async()=>++n===1?{action:{tool:'save_memory',args:{title:'A',content:'B'}}}:{text:'New request'});await runtime.run('old');const id=events.find(e=>e.type==='approval').approvalId;await runtime.run('new');await assert.rejects(runtime.approve(id,true));assert.equal(memory.length,6)});
test('obsolete model that ignores cancellation cannot reenter conversation',async()=>{const {runtime,events}=fixture(async h=>{if(h.at(-1).content==='old'){await sleep(40);return {text:'STALE'}}return {text:'CURRENT'}});const old=runtime.run('old');await sleep(5);await runtime.run('new');await old;assert.deepEqual(events.filter(e=>e.type==='response').map(e=>e.text),['CURRENT'])});
test('delayed tool result is fenced after interruption',async()=>{const {runtime,events}=fixture(async()=>({action:{tool:'search_memory',args:{query:'voice'}}}),{delay:100});const old=runtime.run('search');await sleep(15);runtime.cancel();await old;assert.equal(events.filter(e=>e.type==='tool'||e.type==='response').length,0)});
test('late Rime chunks are fenced even if provider ignores abort',async()=>{const {runtime,events}=fixture(async()=>({text:'Old speech'}),{speech:async(t,s,chunk)=>{chunk([1,2]);await sleep(30);chunk([3,4])}});const old=runtime.run('speak');await sleep(10);runtime.cancel();await old;assert.equal(events.filter(e=>e.type==='audio').length,1);assert.equal(events.filter(e=>e.type==='audio-end').length,0);assert(runtime.history.some(x=>x.content.includes('may not have been heard')))});
test('malformed action parameters are blocked',()=>{assert.equal(evaluate({tool:'save_memory',args:{title:'',content:'x'}}).decision,'block');assert.equal(evaluate({tool:'search_memory',args:{query:4}}).decision,'block')});
test('providers are restricted to loopback',()=>{assert.equal(localURL('http://127.0.0.1:11434'),'http://127.0.0.1:11434');for(const url of ['https://evil.test','http://127.0.0.1.evil.test','file:///etc/passwd','http://user:pass@localhost'])assert.throws(()=>localURL(url))});
test('Rime uses correct contract, streams bytes, and excludes key from body',async()=>{const fetchOriginal=globalThis.fetch;let request;globalThis.fetch=async(url,options)=>{request={url,...options};return new Response(new Uint8Array([0,0,1,0]))};try{const chunks=[];await rime({rimeKey:'test-placeholder',rimeModel:'coda',speaker:'astra',language:'en'})('A short response.',new AbortController().signal,c=>chunks.push(c));assert.equal(request.url,'https://users.rime.ai/v1/rime-tts');assert.equal(request.headers.Accept,'audio/L16');assert.equal(JSON.parse(request.body).modelId,'coda');assert(!request.body.includes('test-placeholder'));assert.equal(chunks.flat().length,4)}finally{globalThis.fetch=fetchOriginal}});
test('live catalog parser validates model speaker language tuple',async()=>{const old=globalThis.fetch;globalThis.fetch=async()=>Response.json({coda:{eng:['astra'],hin:['example']}});try{const c={rimeModel:'coda',speaker:'astra',language:'en'};assert.equal((await validateVoice(c)).speaker,'astra');await assert.rejects(validateVoice({...c,language:'hi'}))}finally{globalThis.fetch=old}});
