const {app,BrowserWindow,ipcMain,session}=require('electron');const fs=require('node:fs');const path=require('node:path');const {pathToFileURL}=require('node:url');
try{process.loadEnvFile(path.join(process.cwd(),'.env'))}catch{}
let win,runtime,config,storage,sttController;const configFromEnv=()=>({ollamaURL:process.env.OLLAMA_URL||'http://127.0.0.1:11434',model:process.env.OLLAMA_MODEL||'qwen3:8b',sttURL:process.env.STT_URL||'http://127.0.0.1:8178/inference',rimeKey:process.env.RIME_API_KEY||'',rimeModel:process.env.RIME_MODEL||'coda',speaker:process.env.RIME_SPEAKER||'astra',language:process.env.RIME_LANGUAGE||'en'});
app.whenReady().then(async()=>{const {Runtime}=await import('../core/runtime.mjs'),{seedMemory}=await import('../core/policy.mjs'),providers=await import('../core/providers.mjs');const dir=app.getPath('userData'),memoryFile=path.join(dir,'memory.json'),auditFile=path.join(dir,'audit.jsonl'),settingsFile=path.join(dir,'settings.json');config=configFromEnv();try{Object.assign(config,JSON.parse(fs.readFileSync(settingsFile,'utf8')))}catch{}storage={read:()=>JSON.parse(fs.readFileSync(memoryFile,'utf8')),add:(m,active)=>{if(!active())return;const data=storage.read();data.push(m);fs.writeFileSync(memoryFile+'.tmp',JSON.stringify(data,null,2),{mode:0o600});if(active())fs.renameSync(memoryFile+'.tmp',memoryFile);else fs.unlinkSync(memoryFile+'.tmp')},audit:event=>fs.appendFileSync(auditFile,JSON.stringify(event)+'\n',{mode:0o600})};if(!fs.existsSync(memoryFile))fs.writeFileSync(memoryFile,JSON.stringify(seedMemory,null,2),{mode:0o600});
const entry=pathToFileURL(path.join(__dirname,'../dist/index.html')).href;win=new BrowserWindow({width:1520,height:980,minWidth:760,minHeight:640,backgroundColor:'#080a10',title:'NOVA × AEGIS',webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});win.removeMenu();win.webContents.setWindowOpenHandler(()=>({action:'deny'}));win.webContents.on('will-navigate',(event,url)=>{if(url!==entry)event.preventDefault()});session.defaultSession.setPermissionRequestHandler((wc,permission,callback,details)=>callback(wc===win.webContents&&permission==='media'&&details.mediaTypes?.every(t=>t==='audio')&&wc.getURL()===entry));session.defaultSession.setPermissionCheckHandler((wc,permission)=>wc===win.webContents&&permission==='media'&&wc.getURL()===entry);
runtime=new Runtime({model:(...args)=>providers.ollama(config)(...args),speech:(...args)=>providers.rime(config)(...args),storage,delay:Math.max(0,Math.min(10000,Number(process.env.NOVA_TEST_TOOL_DELAY_MS)||0)),emit:event=>{if(!win.isDestroyed())win.webContents.send('nova:event',event)}});
function handle(name,fn){ipcMain.handle('nova:'+name,(event,...args)=>{if(event.sender!==win.webContents||event.senderFrame!==win.webContents.mainFrame||event.senderFrame.url!==entry)throw new Error('Untrusted caller.');return fn(...args)})}
handle('send',text=>runtime.run(text));handle('cancel',()=>{sttController?.abort();runtime.cancel()});handle('approve',(id,yes)=>{if(typeof id!=='string'||typeof yes!=='boolean')throw new Error('Invalid approval.');return runtime.approve(id,yes)});handle('memory',()=>storage.read());handle('audit',()=>{try{return fs.readFileSync(auditFile,'utf8').trim().split('\n').filter(Boolean).slice(-200).map(x=>JSON.parse(x))}catch{return []}});handle('heard',turn=>runtime.heard(turn));
handle('status',async()=>{let models=[],ollama=false,voice=null,error='';try{const r=await fetch(providers.localURL(config.ollamaURL)+'/api/tags',{signal:AbortSignal.timeout(3000)});if(!r.ok)throw new Error('Ollama '+r.status);models=(await r.json()).models.map(m=>m.name);ollama=true}catch(e){error=e.message}if(config.rimeKey){try{voice=await providers.validateVoice(config)}catch(e){error+=' '+e.message}}return {mode:'desktop',ollama,models,rime:!!config.rimeKey,voice,error,config:{...config,rimeKey:undefined}}});
handle('configure',value=>{if(runtime.busy||runtime.approvals.pending.size)throw new Error('Interrupt the current task before changing settings.');if(!value||typeof value!=='object')throw new Error('Invalid settings.');for(const key of ['model','speaker','language','rimeModel'])if(typeof value[key]==='string'&&value[key].length<120)config[key]=value[key];for(const key of ['ollamaURL','sttURL'])if(value[key])config[key]=providers.localURL(value[key]);const {rimeKey,...safe}=config;fs.writeFileSync(settingsFile,JSON.stringify(safe,null,2),{mode:0o600});return true});handle('transcribe',async bytes=>{sttController?.abort();sttController=new AbortController();return providers.transcribe(bytes,config,sttController.signal)});win.loadFile(path.join(__dirname,'../dist/index.html'));});app.on('window-all-closed',()=>{runtime?.cancel();app.quit()});
